# Generated by Django 4.1.5 on 2023-02-14 07:53

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0003_rename_text_note_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="user",
            new_name="author",
        ),
        migrations.AddField(
            model_name="note",
            name="share",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
