# Generated by Django 4.1.5 on 2023-02-15 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_note_created_at_note_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="share",
            new_name="share_with",
        ),
    ]
