# Generated by Django 4.1.5 on 2023-02-27 06:16

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0009_notecomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notecomment",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="notes.note",
            ),
        ),
        migrations.AlterField(
            model_name="notehistory",
            name="note",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="version_history",
                to="notes.note",
            ),
        ),
    ]
